### PR TITLE
Add OS/2 Support

### PR DESCRIPTION
**Pull request by komh**
Hi/2.

This is PR for OS/2 support.

1. Disable visibility on OS/2
2. Define MT32EMU_EXPORT_ATTRIBUTE for OS/2

Review, please...

### CODE REVIEW

**Comment by sergm** [comment]
Hi,
would you mind to elaborate please which version of OS/2 can be made compatible yet what compiler do you use? I'm also curious do we need the dllimport declaration in the client applications.

**Comment by komh** [comment]
Hi/2.

1. Minimum version is OS/2 v4.0 + FixPak #13.
2. gcc v9.1.
3. dllimport is not necessary.

Thanks.

**Comment by sergm** [comment]
> gcc v9.1.
If you're sure that the os/2 port of gcc does not recognise __attribute__ ((visibility("default"))). BTW, it seems gcc 9.2 is out there, will it require this change?

**Comment by komh** [comment]
```__attribute__((visibility("default")))__``` is supported as well as ```-fvisibility=default``` by gcc v9.1 and gcc v9.2. However, ```hidden``` is supported at all by neither gcc v9.1 nor gcc v9.2.

**Comment by sergm** [comment]
> `__attribute__((visibility("default")))__` is supported as well as -fvisibility=default by gcc v9.1 and gcc v9.2. However, hidden is supported at all by neither gcc v9.1 nor gcc v9.2.

That doesn't seem to extend to all builds of gcc v9.1 / v9.2 but perhaps is very specific to the os/2 port. I'm unconvinced that things will remain this way forever. Hopefully, as os/2 evolves, support for hidden visibility may be added in the future, since this is a means of creating a good DLL interface for a good operating system. Therefore, I'd rather introduce a cmake configuration option to be translated to a feature-specific preprocessor definition, so that we may be able to trigger support for visibility hidden on/off. That might also be helpful for other platforms where similar problems appear.

**Comment by sergm** [comment]
Oh, wait, we don't actually need any change in globals.h (because gcc supports ` __attribute__ ((visibility("default")))` out of the box), right? So perhaps the only thing to do is to add a cmake option to control whether to apply `set(CMAKE_CXX_VISIBILITY_PRESET hidden)` during the configuration...

**Comment by komh** [comment]
Of course, I'm saying about OS/2 port of gcc only.

And supporting ```__attribute__ ((visibility("default")))``` does not mean it works as expected. It means gcc does not complaing. That's it.

So, modification of globals.h is necessary.

**Comment by sergm** [comment]
OK, I now figured that the os/2 gcc port works nearly the same way as mingw on windows...

**Comment by komh** [comment]
Exactly!

**Pull request merged**
