### PR TITLE
Dedicated audio driver for JACK introduced

### PR DESCRIPTION
**Pull request by dukzcry**
Hi @sergm!
Here is an audio driver for JACK. Partly fixes issue https://sourceforge.net/p/munt/feature-requests/29/
At least there is no more audio delay in case of JACK setup with loopback device https://alsa.opensrc.org/Jack_and_Loopback_device_as_Alsa-to-Jack_bridge

### CODE REVIEW

**Comment by sergm** [comment]
Hi @dukzcry,

I'm glad you want to contribute to the project. Sadly, you didn't notify me about this development, and I'm already busy with the issue https://sourceforge.net/p/munt/feature-requests/29/ you've mentioned, so this PR appears a bit late and a duplicated effort. We have a solution for JACK integration already (that goes beyond just audio support), and it uses a slightly different approach.

As you know, JACK is not merely an audio API but a self-contained system. We're not simply creating an adapter audio driver but rather change our app to be suitable to work with JACK. This involves quite some changes as in the rendering system, but also (and especially) in the MIDI architecture. The ultimate goal here is to get the rendering synchronous, so that we impose 0 additional latency (aside from the implied latency added by the emulation engine itself, e.g. to emulate partial abortion and delays in a physical MIDI interface). Therefore, we move all the code related to communication with JACK into a dedicated class JACKClient. This way we process both the MIDI in and the two audio outputs in a single callback.

Next point, we change QSynth so that we get the interleaved float stream rendered directly, which is then split into two streams as required by JACK. Using integers there is especially undesired if you want better audio quality achieved with the floating point emulation engine.

Also note, when JACK server is running in the realtime mode, the approach used in this PR does not work very well. The realtime thread should never get blocked, and the existing rendering path in QSynth does not currently fit. With the existing solution I experienced occasional dropouts and rarely even crashes in the realtime thread. Therefore, QSynth is to be changed towards lockless operation, e.g. by queuing the pending changes to the synth parameters and shutdown commands.

As for the MIDI subsystem, it's currently only support 1 MIDI driver that is bound with the platform the app is running on. We're going to have JACK MIDI ports configured the same way as usual, and obviously this is quite some work to do as well :)

FYI, I haven't pushed the commit for the existing JACK integration because it is going to be massive enough but not very stable and user-friendly atm. I'll be happy to push it in a branch so you can have a look if interested.

**Comment by dukzcry** [comment]
> I'm glad you want to contribute to the project. Sadly, you didn't notify me about this development, and I'm already busy with the issue https://sourceforge.net/p/munt/feature-requests/29/ you've mentioned, so this PR appears a bit late and a duplicated effort.

No problems, this is just an hour implementation.

> Therefore, we move all the code related to communication with JACK into a dedicated class JACKClient. This way we process both the MIDI in and the two audio outputs in a single callback.

Yes, this is better approach. I went with a quickfix solution :smile:

> Next point, we change QSynth so that we get the interleaved float stream rendered directly, which is then split into two streams as required by JACK. Using integers there is especially undesired if you want better audio quality achieved with the floating point emulation engine.

This is nice. I've seen mt32emu offered floating point rendering interface, but not mt32emu-qt yet.

> With the existing solution I experienced occasional dropouts and rarely even crashes in the realtime thread.

I'm sorry, that never happened to me.

> I'll be happy to push it in a branch so you can have a look if interested.

So proper JACK support led to a quite amout of work. Big kuds for working on this! Yes, please make a branch for it, I would be happy to help with testing :smile:

With nice architecture you described Munt should become a cool real-time JACK instrument!

**Comment by sergm** [comment]
> With nice architecture you described Munt should become a cool real-time JACK instrument!
Yes, this is definitely where we're going to :)

**Comment by DominusExult** [comment]
> I wonder what it would be like to have this different implementation because the one that comes with the project really sucks. Segfaults on JACK directly. Port audio -> jack works but connects to the system output only, and that multiple times, making it really loud. MIDI connectivity is straight up ass.... and I can run anything else flawlessly, from open source synths like Surge XT, to proprietary programs like Renoise. They all work.
> 
> But this POS does not, lol.
> 
> And P.S.: it doesn't even have the decency to dump a core when it segfaults on JACK immediately, and the backtrace in GDB is just: image
> 
> P.P.S.: And what I mean with 'midi is ass' is: It doesn't work, at all, vmpk ( a virtual midi keyboard?) nope. Renoise (which is usually excellent with midi) nope. What does work is the demo songs, so that's why I know that port audio works. Otherwise, the midi input is just not working. In fact, I hate the user interface too, the different tabs, and I cannot close them, and blahdeebloo.
> 
> Trim that shit down, or make a JACK version of the alsa CLI backend, or something. I'd love a headless version of this.

learn to be respectful and how to make pull requests.

**Comment by sergm** [comment]
@DominusExult Thanks! For future reference, see #106

**Pull request closed without merging**
